apiVersion: v1
kind: Service
metadata:
  name: api-gateway-cluster-ip-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  type: ClusterIP
  selector:
    component: api-gateway
  ports:
    - port: 5000
      targetPort: 5000

