apiVersion: v1
kind: Service
metadata:
  name: moods-api-cluster-ip-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5002"
spec:
  type: ClusterIP
  selector:
    component: moods-api
  ports:
    - port: 5002
      targetPort: 5002
