apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "api-gateway"
        static_configs:
          - targets: ["api-gateway-cluster-ip-service:5000"]

      - job_name: "server-main"
        static_configs:
          - targets: ["server-cluster-ip-service:5001"]

      - job_name: "moods-api"
        static_configs:
          - targets: ["moods-api-cluster-ip-service:5002"]

      - job_name: "stats-api"
        static_configs:
          - targets: ["stats-api-cluster-ip-service:5003"]


